### ISSUE TITLE
1月18日pafd自动填写又失效了

### ISSUE THREAD

**Issue by eslgf** [FDUCSLG/pafd-automated#28]
exit code 1，有人遇见一样的问题吗

**Comment by RuBP17** [comment]
同时登陆服务器的人太多了，学校的土豆炸掉了，建议自己改一改自动填报时间

**Comment by abcdhhhh** [comment]
+1

**Comment by RuBP17** [comment]
把automate.yml里cron那一行的数字改一下应该就行。

**Comment by eslgf** [comment]
刚刚手动重试了一次，还是失败，感觉可能不是服务器的问题？

**Comment by RuBP17** [comment]
但我手动重试了一次，他成功运行了。加一个while true: Try?

**Comment by zhangliao-legend** [comment]
> 

有道理哇

**Comment by RuBP17** [comment]
我检查了一下，是https://uis.fudan.edu.cn这个网址有时候会登不上去。
呜呜呜，我的elearning也登不上了。

**Comment by ansselmu** [comment]
+1 
`Traceback (most recent call last):
  File "main.py", line 282, in <module>
    daily_fudan.check()
  File "main.py", line 146, in check
    print("◉上一次提交日期为:", last_info["d"]["info"]["date"])
TypeError: 'bool' object is not subscriptable
Error: Process completed with exit code 1.`
